CELLBASE_HOST = "http://ws-beta.bioinfo.cipf.es/cellbase/rest";
CELLBASE_HOST = "http://ws-beta.bioinfo.cipf.es/cellbase-mongo/rest";
OPENCGA_HOST = "http://ws-beta.bioinfo.cipf.es/opencga-server-beta/rest";

HEADER_HOME_LINK = "https://github.com/opencb/cellbrowser";
HEADER_HELP_LINK = "https://github.com/opencb/cellbrowser";
HEADER_TUTORIAL_LINK = "https://github.com/opencb/cellbrowser/wiki";
HEADER_ABOUT_HTML = "";

EXAMPLE_1_JSON = '{"graph":{"vertices":[{"id":"vnpWxUf3Y2h","name":"B"},{"id":"v558yRsjWew","name":"C"},{"id":"vr9iairfpAS","name":"D"},{"id":"vpttQr7zlMi","name":"E"},{"id":"vmMvUq4BKqo","name":"A"}],"edges":[{"id":"etVKfYJH3PI","name":"","source":{"id":"vnpWxUf3Y2h","name":"B"},"target":{"id":"v558yRsjWew","name":"C"}},{"id":"eV34XJcwIM1","name":"","source":{"id":"v558yRsjWew","name":"C"},"target":{"id":"vr9iairfpAS","name":"D"}},{"id":"e9EDXfi8ERf","name":"","source":{"id":"vr9iairfpAS","name":"D"},"target":{"id":"vpttQr7zlMi","name":"E"}},{"id":"eU2kdYP1u2J","name":"","source":{"id":"vpttQr7zlMi","name":"E"},"target":{"id":"vnpWxUf3Y2h","name":"B"}},{"id":"e5WRUXTfmXO","name":"","source":{"id":"vmMvUq4BKqo","name":"A"},"target":{"id":"vnpWxUf3Y2h","name":"B"}}]},"config":{"vertices":{"vnpWxUf3Y2h":{"id":"vnpWxUf3Y2h","coords":{"x":185,"y":61},"renderer":{"shape":"ellipse","size":40,"color":"#ff7537","strokeSize":5,"strokeColor":"#f83a22","opacity":"1","labelSize":12,"labelColor":"#111111"}},"v558yRsjWew":{"id":"v558yRsjWew","coords":{"x":352,"y":61},"renderer":{"shape":"rectangle","size":35,"color":"#b3dc6c","strokeSize":4,"strokeColor":"#16a765","opacity":1,"labelSize":12,"labelColor":"#111111"}},"vr9iairfpAS":{"id":"vr9iairfpAS","coords":{"x":435,"y":207},"renderer":{"shape":"circle","size":45,"color":"#9fc6e7","strokeSize":6,"strokeColor":"#4986e7","opacity":1,"labelSize":12,"labelColor":"#111111"}},"vpttQr7zlMi":{"id":"vpttQr7zlMi","coords":{"x":254,"y":207},"renderer":{"shape":"square","size":40,"color":"#fbe983","strokeSize":8,"strokeColor":"#fad165","opacity":1,"labelSize":12,"labelColor":"#111111"}},"vmMvUq4BKqo":{"id":"vmMvUq4BKqo","coords":{"x":46,"y":148},"renderer":{"shape":"circle","size":40,"color":"#cccccc","strokeSize":3,"strokeColor":"#888888","opacity":1,"labelSize":12,"labelColor":"#111111"}}},"edges":{"etVKfYJH3PI":{"id":"etVKfYJH3PI","renderer":{"shape":"directed","size":2,"color":"#888888","strokeSize":2,"strokeColor":"#aaaaaa","opacity":1,"labelSize":12,"labelColor":"#111111"}},"eV34XJcwIM1":{"id":"eV34XJcwIM1","renderer":{"shape":"directed","size":2,"color":"#4986e7","strokeSize":2,"strokeColor":"#aaaaaa","opacity":1,"labelSize":12,"labelColor":"#111111"}},"e9EDXfi8ERf":{"id":"e9EDXfi8ERf","renderer":{"shape":"directed","size":2,"color":"#888888","strokeSize":2,"strokeColor":"#aaaaaa","opacity":1,"labelSize":12,"labelColor":"#111111"}},"eU2kdYP1u2J":{"id":"eU2kdYP1u2J","renderer":{"shape":"directed","size":2,"color":"#888888","strokeSize":2,"strokeColor":"#aaaaaa","opacity":1,"labelSize":12,"labelColor":"#111111"}},"e5WRUXTfmXO":{"id":"e5WRUXTfmXO","renderer":{"shape":"directed","size":2,"color":"#888888","strokeSize":2,"strokeColor":"#aaaaaa","opacity":1,"labelSize":12,"labelColor":"#111111"}}},"general":{}}}';
EXAMPLE_2_JSON = '';
